### ISSUE TITLE
Remove Travis-Ci and GCP related code

### ISSUE THREAD

**Issue by zbeucler2018** [Farama-Foundation/stable-retro#1]
There is a good amount of code related to Travis-ci and GCP (Google Cloud Platform) that is no longer needed. This code should be removed to reduce clutter and tech dept

**Comment by onaclov2000** [comment]
Just to confirm we'd want to remove stuff like travis.py, .travis.yaml, those contain the GCP code (also check if anything calls them).  

I suppose the relevant Dockerfile code too? (https://github.com/Farama-Foundation/stable-retro/blob/master/docker/linux/Dockerfile) 

Any other obvious things I am missing?

**Comment by onaclov2000** [comment]
Yes, sorry, I was meaning there is GCP stuff in the dockerfile, I wasn't meaning to outright remove it.

**Comment by onaclov2000** [comment]
Do we have a place we are putting the original travis related code? It seems like just flat out tossing it would maybe be a bad idea, we should make sure if we are pulling travis code out, it's going into dockerfiles (if docker is the path, or whatever CI ).

I.E. I was about to delete:
* https://github.com/onaclov2000/stable-retro-1/blob/onaclov2000-patch-1/cores/gba/.travis-deps.sh

And realized if people didn't know that existed in the future we might have other issues and folks will have to do deep diving to find these things

**Comment by pseudo-rnd-thoughts** [comment]
Good point, we can always revert the code to the old version to find these changes so I won't worry about it

**Comment by pseudo-rnd-thoughts** [comment]
Is this done now?

**Comment by onaclov2000** [comment]
Do we want to remove Travis files in the cores subdirectory? I haven't done that yet, but can pull them out and make a PR. (I dont know how many there are it may just be GBA but I can do a quick search)

**Comment by onaclov2000** [comment]
There seemed to be a bit of overlap, I think someone else removed some Travis stuff, but inside the dockerfile there are still references to Google cloud stuff.

**Comment by pseudo-rnd-thoughts** [comment]
> Do we want to remove Travis files in the cores subdirectory? I haven't done that yet, but can pull them out and make a PR. (I dont know how many there are it may just be GBA but I can do a quick search)

It seems to me that the original project, copy and pasted the emulators from projects which includes travis for testing. 

As this was part of the original emulators, I'm in favor of not modifying any of the emulators (except for updating the whole project to a new version if possible)

> There seemed to be a bit of overlap, I think someone else removed some Travis stuff, but inside the dockerfile there are still references to Google cloud stuff.

Which file are you referencing?

**Comment by pseudo-rnd-thoughts** [comment]
@onaclov2000 Could you try removing as much of those install as possible then we can close this issue

**Comment by onaclov2000** [comment]
Pull Request submitted.

**Comment by onaclov2000** [comment]
This can be closed.
