### ISSUE TITLE
Error: Could not build wheel for stable-retro

### ISSUE THREAD

**Issue by dadal00** [Farama-Foundation/stable-retro#100]
## Issue summary

I've been trying to install stable-retro but I keep getting the same error. I tried downgrading the setup tools and wheel versions but to no luck.

Building wheels for collected packages: stable-retro
  Building wheel for stable-retro (pyproject.toml): started
  Building wheel for stable-retro (pyproject.toml): finished with status 'error'
Failed to build stable-retro
Note: you may need to restart the kernel to use updated packages.
  Running command git clone --filter=blob:none --quiet https://github.com/Farama-Foundation/stable-retro.git 'C:\Users\Dylan\AppData\Local\Temp\pip-req-build-spzkpvdq'
  error: subprocess-exited-with-error
  
  × Building wheel for stable-retro (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7336 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\retro
      copying retro\enums.py -> build\lib.win-amd64-cpython-310\retro
      copying retro\rendering.py -> build\lib.win-amd64-cpython-310\retro
      copying retro\retro_env.py -> build\lib.win-amd64-cpython-310\retro
      copying retro\__init__.py -> build\lib.win-amd64-cpython-310\retro
      creating build\lib.win-amd64-cpython-310\retro\data
      copying retro\data\__init__.py -> build\lib.win-amd64-cpython-310\retro\data
      creating build\lib.win-amd64-cpython-310\retro\data\stable
      copying retro\data\stable\__init__.py -> build\lib.win-amd64-cpython-310\retro\data\stable
      creating build\lib.win-amd64-cpython-310\retro\data\experimental
      copying retro\data\experimental\__init__.py -> build\lib.win-amd64-cpython-310\retro\data\experimental
      creating build\lib.win-amd64-cpython-310\retro\data\contrib
      copying retro\data\contrib\__init__.py -> build\lib.win-amd64-cpython-310\retro\data\contrib
      creating build\lib.win-amd64-cpython-310\retro\scripts
...
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for stable-retro
ERROR: Could not build wheels for stable-retro, which is required to install pyproject.toml-based projects

## System information

- Windows
- Python 3.10.11
- I'm not sure what the version of the Gym Retro is.

**Comment by MatPoliquin** [comment]
Currently Windows native is not supported, you need to use WSL2 (Windows Subsystem for Linux)
It's relatively easy to setup, once you have WSL2, you can install Ubuntu 20.04/22.04 from the Windows Store

**Comment by dadal00** [comment]
Thank you so much. It worked.
