### ISSUE TITLE
Documentation Cleanup

### ISSUE THREAD

**Issue by onaclov2000** [Farama-Foundation/stable-retro#19]
## Issue summary
There is a lot of broken links/etc. I mentioned this in another issue but think it might be good to have as it's own issue. There are links and references that require updating. See below for the list of what I find as I go along (I'll add as I go). This would be a good issue for someone who doesn't know how to code likely. (And/or a good first issue too).

- [ ] https://github.com/Farama-Foundation/stable-retro/blob/master/docs/integration.rst
    - [x] gym.openai.com
    - [ ] [Windows Integration UI](https://storage.googleapis.com/gym-retro/builds/Gym%20Retro-latest-win64.zip)
    - [ ] [Mac Integration UI](https://storage.googleapis.com/gym-retro/builds/Gym%20Retro-latest-Darwin.dmg)
- [ ] https://github.com/Farama-Foundation/stable-retro/blob/master/README.md
    - [x] gym.openai.com

**Comment by pseudo-rnd-thoughts** [comment]
https://github.com/Farama-Foundation/stable-retro/pull/23 has started the website transfer process
