### ISSUE TITLE
Error when installing with git via pip

### ISSUE THREAD

**Issue by zbeucler2018** [Farama-Foundation/stable-retro#33]
When installing the repo with the method in the readme: `pip3 install git+https://github.com/Farama-Foundation/stable-retro.git`, the following error pops up after importing the package:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/dist-packages/retro/__init__.py", line 11, in <module>
    with open(os.path.join(os.path.dirname(__file__), "../VERSION")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/retro/../VERSION'
```

### Steps to reproduce
- run `pip3 install git+https://github.com/Farama-Foundation/stable-retro.git`
- run `import retro`

**Comment by pseudo-rnd-thoughts** [comment]
In the original project there were two VERSION files, I removed one of them. I suspect we just don't need the `..` part, it should be just `retro/VERSION`

**Comment by zbeucler2018** [comment]
Agreed. I can make a PR later tonight for this change
