### ISSUE TITLE
New version issue with latest git commit

### ISSUE THREAD

**Issue by CarsonStevens** [Farama-Foundation/stable-retro#70]
After a clean pip install git+https://github.com/Farama-Foundation/stable-retro.git

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-6-2fedbd23030f>](https://localhost:8080/#) in <cell line: 2>()
      ----> 1 import retro; print(retro.__path__)

[/usr/local/lib/python3.10/dist-packages/retro/__init__.py](https://localhost:8080/#) in <module>
      9 core_path(os.path.join(os.path.dirname(__file__), "cores"))
     10 
---> 11 with open(os.path.join(os.path.dirname(__file__), "VERSION.txt")) as f:
     12     __version__ = f.read()
     13 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/retro/VERSION.txt'

This is on a Colab T4

**Comment by zbeucler2018** [comment]
[This MR](https://github.com/Farama-Foundation/stable-retro/pull/71) fixes this error

**Comment by MatPoliquin** [comment]
Fix is merged now

**Comment by CarsonStevens** [comment]
Thank you for the quick fix
